meilisearch:
  api_url: http://host.docker.internal:7700/
#  api_key: 'MEILISEARCH_API_KEY'  #TODO
  insert_size: 8008
  insert_interval: 10
source:
  type: postgres
  host: 127.0.0.1 # assuming your PostgreSQL server is running on the same machine as `meilisync`
  port: 5432
  database: jdbc:postgresql://localhost:5432/GAMEDEX
  user: test # This should be changed
  password: test # This should be changed
sync:
  - table: GAME
    pk: GAME_ID
    full: true