version: '3.7'
services:
  database:
    image: postgis/postgis:12-3.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: GAMEDEX
      PG_DB: GAMEDEX
