version: '3.7'
services:
  frontend:
    extends:
      file: angular/docker-compose-frontend.yaml
      service: frontend
  backend:
    extends:
      file: docker-compose-backend.yaml
      service: backend
  database:
    extends:
      file: docker-compose-postgres.yaml
      service: database
