version: '3.7'
services:
  database:
    image: postgis/postgis:12-3.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: GAMEDEX
      PG_DB: GAMEDEX
  backend:
    build: ./
    ports:
      - 8080:8080
    environment:
      spring.datasource.jdbcUrl: "jdbc:postgresql://database:5432/GAMEDEX"
  frontend:
    build: angular/ .
    ports:
      - 4200:80
    links:
      - backend