version: '3.7'
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test #This should really be changed lol
      POSTGRES_DB: GAMEDEX
      PG_DB: GAMEDEX
    restart: always
    networks:
      - gamedex
  backend:
    build: ./
    restart: always
    container_name: game_service
    ports:
      - 8080:8080
    environment:
      spring.datasource.jdbcUrl: "jdbc:postgresql://database:5432/GAMEDEX"
    networks:
      - gamedex
  frontend:
    build: angular/.
    container_name: angular
    ports:
      - 4200:80
    restart: always
    networks:
      - gamedex
  search:
    build: search/.
    container_name: search_service
    ports:
      - 8001:8001
    restart: always
    networks:
      - gamedex
    depends_on:
      - meilisearch
  cache:
    build: cache/.
    container_name: cache_service
    ports:
      - 8002:8002
    restart: always
    networks:
      - gamedex
    depends_on:
      - redis
  meilisearch:
    image: getmeili/meilisearch:v1.5
    restart: always
    container_name: meilisearch
    environment:
      - MEILI_HTTP_PAYLOAD_SIZE_LIMIT=1048576000 # 1 gigabyte
    volumes:
      - meili:/data.ms
    ports:
      - 7700:7700
    networks:
      - gamedex
  redis:
    image: redis/redis-stack-server
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - gamedex

#  meilisync:   TODO this is a nice to have.
#    platform: linux/x86_64
#    image: long2ice/meilisync
#    restart: always
#    volumes:
#      - ./config.yml:/meilisync/config.yml
#    networks:
#      - gamedex

networks:
  gamedex:
    external: false

volumes:
  meili:
    driver: local