version: '3.7'
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test #This should really be changed lol
      POSTGRES_DB: GAMEDEX
      PG_DB: GAMEDEX
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    restart: always
    networks:
      - gamedex
  backend:
    build: ./
    restart: always
    ports:
      - 8080:8080
    environment:
      spring.datasource.jdbcUrl: "jdbc:postgresql://database:5432/GAMEDEX"
    networks:
      - gamedex
  frontend:
    build: angular/ .
    ports:
      - 4200:80
    links:
      - backend
    restart: always
    networks:
      - gamedex
  search:
    image: getmeili/meilisearch:v1.5
    restart: always
    container_name: search
    environment:
      - MEILI_HTTP_PAYLOAD_SIZE_LIMIT=1048576000 # 1 gigabyte
    volumes:
      - meili:/data.ms
    ports:
      - 7700:7700
    networks:
      - gamedex
#  meilisync:   TODO this is a nice to have.
#    platform: linux/x86_64
#    image: long2ice/meilisync
#    restart: always
#    volumes:
#      - ./config.yml:/meilisync/config.yml
#    networks:
#      - gamedex

networks:
  gamedex:
    external: false

volumes:
  meili:
    driver: local